CREATE TABLE users (id SERIAL PRIMARY KEY,username VARCHAR(50) UNIQUE NOT NULL,email VARCHAR(100) UNIQUE NOT NULL,hashed_password VARCHAR(100) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE boards(id SERIAL PRIMARY KEY,user_id INTEGER NOT NULL,title VARCHAR(100),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id))

CREATE TABLE lists(id SERIAL PRIMARY KEY,board_id INTEGER NOT NULL,title VARCHAR(100),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (board_id) REFERENCES boards(id));

CREATE TABLE cards(id SERIAL PRIMARY KEY,list_id INTEGER NOT NULL,title VARCHAR(100) NOT NULL,task_description TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (list_id) REFERENCES list(id));